pytest:
  stage: test
  image: yourlabs/pytezos
  script:
  - pip install .
  - py.test -v
  services:
  - name: yourlabs/tezos
    alias: tz

pypi:
  stage: deploy
  script: pypi-release
  image: yourlabs/python
